<?php

namespace App\Domains\ETA\Models;

use App\Domains\ETA\Models\Concerns\HasTranslations;
use Illuminate\Database\Eloquent\Model;
use Sushi\Sushi;

class CountryCodes extends Model
{
    use Sushi;
    use HasTranslations;

    /**
     * Get Sushi array record.
     *
     * @var array
     */
    protected array $rows = [
        ['code' => 'AD', 'desc_en' => 'Andorra', 'desc_ar' => 'أندورا'],
        [
            'code' => 'AE',
            'desc_en' => 'United Arab Emirates',
            'desc_ar' => 'الامارات العربية المتحدة',
        ],
        ['code' => 'AF', 'desc_en' => 'Afghanistan', 'desc_ar' => 'أفغانستان'],
        [
            'code' => 'AG',
            'desc_en' => 'Antigua and Barbuda',
            'desc_ar' => 'أنتيغوا وباربودا',
        ],
        ['code' => 'AI', 'desc_en' => 'Anguilla', 'desc_ar' => 'أنجويلا'],
        ['code' => 'AL', 'desc_en' => 'Albania', 'desc_ar' => 'ألبانيا'],
        ['code' => 'AM', 'desc_en' => 'Armenia', 'desc_ar' => 'أرمينيا'],
        ['code' => 'AO', 'desc_en' => 'Angola', 'desc_ar' => 'أنجولا'],
        [
            'code' => 'AQ',
            'desc_en' => 'Antarctica',
            'desc_ar' => 'القارة القطبية الجنوبية',
        ],
        ['code' => 'AR', 'desc_en' => 'Argentina', 'desc_ar' => 'الأرجنتين'],
        [
            'code' => 'AS',
            'desc_en' => 'American Samoa',
            'desc_ar' => 'ساموا الأمريكية',
        ],
        ['code' => 'AT', 'desc_en' => 'Austria', 'desc_ar' => 'النمسا'],
        ['code' => 'AU', 'desc_en' => 'Australia', 'desc_ar' => 'أستراليا'],
        ['code' => 'AW', 'desc_en' => 'Aruba', 'desc_ar' => 'آروبا'],
        ['code' => 'AX', 'desc_en' => 'Åland Islands', 'desc_ar' => 'جزر أولان'],
        ['code' => 'AZ', 'desc_en' => 'Azerbaijan', 'desc_ar' => 'أذربيجان'],
        [
            'code' => 'BA',
            'desc_en' => 'Bosnia and Herzegovina',
            'desc_ar' => 'البوسنة والهرسك',
        ],
        ['code' => 'BB', 'desc_en' => 'Barbados', 'desc_ar' => 'بربادوس'],
        ['code' => 'BD', 'desc_en' => 'Bangladesh', 'desc_ar' => 'بنجلاديش'],
        ['code' => 'BE', 'desc_en' => 'Belgium', 'desc_ar' => 'بلجيكا'],
        ['code' => 'BF', 'desc_en' => 'Burkina Faso', 'desc_ar' => 'بوركينا فاسو'],
        ['code' => 'BG', 'desc_en' => 'Bulgaria', 'desc_ar' => 'بلغاريا'],
        ['code' => 'BH', 'desc_en' => 'Bahrain', 'desc_ar' => 'البحرين'],
        ['code' => 'BI', 'desc_en' => 'Burundi', 'desc_ar' => 'بوروندي'],
        ['code' => 'BJ', 'desc_en' => 'Benin', 'desc_ar' => 'بنين'],
        [
            'code' => 'BL',
            'desc_en' => 'Saint Barthelemy',
            'desc_ar' => 'سان بارتيلمي',
        ],
        ['code' => 'BM', 'desc_en' => 'Bermuda', 'desc_ar' => 'برمودا'],
        ['code' => 'BN', 'desc_en' => 'Brunei Darussalam', 'desc_ar' => 'بروناي'],
        [
            'code' => 'BO',
            'desc_en' => 'Bolivia (Plurinational State of)',
            'desc_ar' => 'بوليفيا',
        ],
        [
            'code' => 'BQ',
            'desc_en' => 'Bonaire, Sint Eustatius and Saba',
            'desc_ar' => 'الجزر الكاريبية الهولندية',
        ],
        ['code' => 'BR', 'desc_en' => 'Brazil', 'desc_ar' => 'البرازيل'],
        ['code' => 'BS', 'desc_en' => 'Bahamas', 'desc_ar' => 'الباهاما'],
        ['code' => 'BT', 'desc_en' => 'Bhutan', 'desc_ar' => 'بوتان'],
        ['code' => 'BV', 'desc_en' => 'Bouvet Island', 'desc_ar' => 'جزيرة بوفيه'],
        ['code' => 'BW', 'desc_en' => 'Botswana', 'desc_ar' => 'بتسوانا'],
        ['code' => 'BY', 'desc_en' => 'Belarus', 'desc_ar' => 'روسيا البيضاء'],
        ['code' => 'BZ', 'desc_en' => 'Belize', 'desc_ar' => 'بليز'],
        ['code' => 'CA', 'desc_en' => 'Canada', 'desc_ar' => 'كندا'],
        [
            'code' => 'CC',
            'desc_en' => 'Cocos (Keeling) Islands',
            'desc_ar' => 'جزر كوكوس',
        ],
        [
            'code' => 'CD',
            'desc_en' => 'Congo (Democratic Republic of the)',
            'desc_ar' => 'جمهورية الكونغو الديمقراطية',
        ],
        [
            'code' => 'CF',
            'desc_en' => 'Central African Republic',
            'desc_ar' => 'جمهورية أفريقيا الوسطى',
        ],
        ['code' => 'CG', 'desc_en' => 'Congo', 'desc_ar' => 'جمهورية الكونغو'],
        ['code' => 'CH', 'desc_en' => 'Switzerland', 'desc_ar' => 'سويسرا'],
        ['code' => 'CI', 'desc_en' => 'Cote d’Ivoire', 'desc_ar' => 'ساحل العاج'],
        ['code' => 'CK', 'desc_en' => 'Cook Islands', 'desc_ar' => 'جزر كوك'],
        ['code' => 'CL', 'desc_en' => 'Chile', 'desc_ar' => 'شيلي'],
        ['code' => 'CM', 'desc_en' => 'Cameroon', 'desc_ar' => 'الكاميرون'],
        ['code' => 'CN', 'desc_en' => 'China', 'desc_ar' => 'الصين'],
        ['code' => 'CO', 'desc_en' => 'Colombia', 'desc_ar' => 'كولومبيا'],
        ['code' => 'CR', 'desc_en' => 'Costa Rica', 'desc_ar' => 'كوستاريكا'],
        ['code' => 'CU', 'desc_en' => 'Cuba', 'desc_ar' => 'كوبا'],
        ['code' => 'CV', 'desc_en' => 'Cabo Verde', 'desc_ar' => 'الرأس الأخضر'],
        ['code' => 'CW', 'desc_en' => 'Curaçao', 'desc_ar' => 'كوراساو'],
        [
            'code' => 'CX',
            'desc_en' => 'Christmas Island',
            'desc_ar' => 'جزيرة عيد الميلاد',
        ],
        ['code' => 'CY', 'desc_en' => 'Cyprus', 'desc_ar' => 'قبرص'],
        ['code' => 'CZ', 'desc_en' => 'Czechia', 'desc_ar' => 'جمهورية التشيك'],
        ['code' => 'DE', 'desc_en' => 'Germany', 'desc_ar' => 'ألمانيا'],
        ['code' => 'DJ', 'desc_en' => 'Djibouti', 'desc_ar' => 'جيبوتي'],
        ['code' => 'DK', 'desc_en' => 'Denmark', 'desc_ar' => 'الدانمرك'],
        ['code' => 'DM', 'desc_en' => 'Dominica', 'desc_ar' => 'دومينيكا'],
        [
            'code' => 'DO',
            'desc_en' => 'Dominican Republic',
            'desc_ar' => 'جمهورية الدومينيكان',
        ],
        ['code' => 'DZ', 'desc_en' => 'Algeria', 'desc_ar' => 'الجزائر'],
        ['code' => 'EC', 'desc_en' => 'Ecuador', 'desc_ar' => 'الاكوادور'],
        ['code' => 'EE', 'desc_en' => 'Estonia', 'desc_ar' => 'استونيا'],
        ['code' => 'EG', 'desc_en' => 'Egypt', 'desc_ar' => 'مصر'],
        [
            'code' => 'EH',
            'desc_en' => 'Western Sahara',
            'desc_ar' => 'الصحراء الغربية',
        ],
        ['code' => 'ER', 'desc_en' => 'Eritrea', 'desc_ar' => 'اريتريا'],
        ['code' => 'ES', 'desc_en' => 'Spain', 'desc_ar' => 'أسبانيا'],
        ['code' => 'ET', 'desc_en' => 'Ethiopia', 'desc_ar' => 'اثيوبيا'],
        ['code' => 'FI', 'desc_en' => 'Finland', 'desc_ar' => 'فنلندا'],
        ['code' => 'FJ', 'desc_en' => 'Fiji', 'desc_ar' => 'فيجي'],
        [
            'code' => 'FK',
            'desc_en' => 'Falkland Islands (Malvinas)',
            'desc_ar' => 'جزر فوكلاند',
        ],
        [
            'code' => 'FM',
            'desc_en' => 'Micronesia (Federated States of)',
            'desc_ar' => 'ميكرونيزيا',
        ],
        ['code' => 'FO', 'desc_en' => 'Faroe Islands', 'desc_ar' => 'جزر فارو'],
        ['code' => 'FR', 'desc_en' => 'France', 'desc_ar' => 'فرنسا'],
        ['code' => 'GA', 'desc_en' => 'Gabon', 'desc_ar' => 'الجابون'],
        [
            'code' => 'GB',
            'desc_en' => 'United Kingdom of Great Britain and Northern Ireland',
            'desc_ar' => 'المملكة المتحدة',
        ],
        ['code' => 'GD', 'desc_en' => 'Grenada', 'desc_ar' => 'جرينادا'],
        ['code' => 'GE', 'desc_en' => 'Georgia', 'desc_ar' => 'جورجيا'],
        ['code' => 'GF', 'desc_en' => 'French Guiana', 'desc_ar' => 'غويانا'],
        ['code' => 'GG', 'desc_en' => 'Guernsey', 'desc_ar' => 'جيرنزي'],
        ['code' => 'GH', 'desc_en' => 'Ghana', 'desc_ar' => 'غانا'],
        ['code' => 'GI', 'desc_en' => 'Gibraltar', 'desc_ar' => 'جبل طارق'],
        ['code' => 'GL', 'desc_en' => 'Greenland', 'desc_ar' => 'جرينلاند'],
        ['code' => 'GM', 'desc_en' => 'Gambia', 'desc_ar' => 'غامبيا'],
        ['code' => 'GN', 'desc_en' => 'Guinea', 'desc_ar' => 'غينيا'],
        ['code' => 'GP', 'desc_en' => 'Guadeloupe', 'desc_ar' => 'جوادلوب'],
        [
            'code' => 'GQ',
            'desc_en' => 'Equatorial Guinea',
            'desc_ar' => 'غينيا الاستوائية',
        ],
        ['code' => 'GR', 'desc_en' => 'Greece', 'desc_ar' => 'اليونان'],
        [
            'code' => 'GS',
            'desc_en' => 'South Georgia and the South Sandwich Islands',
            'desc_ar' => 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
        ],
        ['code' => 'GT', 'desc_en' => 'Guatemala', 'desc_ar' => 'جواتيمالا'],
        ['code' => 'GU', 'desc_en' => 'Guam', 'desc_ar' => 'جوام'],
        ['code' => 'GW', 'desc_en' => 'Guinea-Bissau', 'desc_ar' => 'غينيا بيساو'],
        ['code' => 'GY', 'desc_en' => 'Guyana', 'desc_ar' => 'غيانا'],
        ['code' => 'HK', 'desc_en' => 'Hong Kong', 'desc_ar' => 'هونغ كونغ'],
        [
            'code' => 'HM',
            'desc_en' => 'Heard Island and McDonald Islands',
            'desc_ar' => 'جزيرة هيرد وجزر ماكدونالد',
        ],
        ['code' => 'HN', 'desc_en' => 'Honduras', 'desc_ar' => 'هندوراس'],
        ['code' => 'HR', 'desc_en' => 'Croatia', 'desc_ar' => 'كرواتيا'],
        ['code' => 'HT', 'desc_en' => 'Haiti', 'desc_ar' => 'هايتي'],
        ['code' => 'HU', 'desc_en' => 'Hungary', 'desc_ar' => 'المجر'],
        ['code' => 'ID', 'desc_en' => 'Indonesia', 'desc_ar' => 'اندونيسيا'],
        ['code' => 'IE', 'desc_en' => 'Ireland', 'desc_ar' => 'أيرلندا'],
        ['code' => 'IL', 'desc_en' => 'Israel', 'desc_ar' => 'اسرائيل'],
        ['code' => 'IM', 'desc_en' => 'Isle of Man', 'desc_ar' => 'جزيرة مان'],
        ['code' => 'IN', 'desc_en' => 'India', 'desc_ar' => 'الهند'],
        [
            'code' => 'IO',
            'desc_en' => 'British Indian Ocean Territory',
            'desc_ar' => 'إقليم المحيط الهندي البريطاني',
        ],
        ['code' => 'IQ', 'desc_en' => 'Iraq', 'desc_ar' => 'العراق'],
        [
            'code' => 'IR',
            'desc_en' => 'Iran (Islamic Republic of)',
            'desc_ar' => 'ايران',
        ],
        ['code' => 'IS', 'desc_en' => 'Iceland', 'desc_ar' => 'أيسلندا'],
        ['code' => 'IT', 'desc_en' => 'Italy', 'desc_ar' => 'ايطاليا'],
        ['code' => 'JE', 'desc_en' => 'Jersey', 'desc_ar' => 'جيرسي'],
        ['code' => 'JM', 'desc_en' => 'Jamaica', 'desc_ar' => 'جامايكا'],
        ['code' => 'JO', 'desc_en' => 'Jordan', 'desc_ar' => 'الأردن'],
        ['code' => 'JP', 'desc_en' => 'Japan', 'desc_ar' => 'اليابان'],
        ['code' => 'KE', 'desc_en' => 'Kenya', 'desc_ar' => 'كينيا'],
        ['code' => 'KG', 'desc_en' => 'Kyrgyzstan', 'desc_ar' => 'قرغيزستان'],
        ['code' => 'KH', 'desc_en' => 'Cambodia', 'desc_ar' => 'كمبوديا'],
        ['code' => 'KI', 'desc_en' => 'Kiribati', 'desc_ar' => 'كيريباتي'],
        ['code' => 'KM', 'desc_en' => 'Comoros', 'desc_ar' => 'جزر القمر'],
        [
            'code' => 'KN',
            'desc_en' => 'Saint Kitts and Nevis',
            'desc_ar' => 'سانت كيتس ونيفيس',
        ],
        [
            'code' => 'KP',
            'desc_en' => 'Korea (Democratic People’s Republic of)',
            'desc_ar' => 'كوريا الشمالية',
        ],
        [
            'code' => 'KR',
            'desc_en' => 'Korea (Republic of)',
            'desc_ar' => 'كوريا الجنوبية',
        ],
        ['code' => 'KW', 'desc_en' => 'Kuwait', 'desc_ar' => 'الكويت'],
        ['code' => 'KY', 'desc_en' => 'Cayman Islands', 'desc_ar' => 'جزر كايمان'],
        ['code' => 'KZ', 'desc_en' => 'Kazakhstan', 'desc_ar' => 'كازاخستان'],
        [
            'code' => 'LA',
            'desc_en' => 'Lao People’s Democratic Republic',
            'desc_ar' => 'لاوس',
        ],
        ['code' => 'LB', 'desc_en' => 'Lebanon', 'desc_ar' => 'لبنان'],
        ['code' => 'LC', 'desc_en' => 'Saint Lucia', 'desc_ar' => 'سانت لوسيا'],
        ['code' => 'LI', 'desc_en' => 'Liechtenstein', 'desc_ar' => 'ليختنشتاين'],
        ['code' => 'LK', 'desc_en' => 'Sri Lanka', 'desc_ar' => 'سريلانكا'],
        ['code' => 'LR', 'desc_en' => 'Liberia', 'desc_ar' => 'ليبيريا'],
        ['code' => 'LS', 'desc_en' => 'Lesotho', 'desc_ar' => 'ليسوتو'],
        ['code' => 'LT', 'desc_en' => 'Lithuania', 'desc_ar' => 'ليتوانيا'],
        ['code' => 'LU', 'desc_en' => 'Luxembourg', 'desc_ar' => 'لوكسمبورج'],
        ['code' => 'LV', 'desc_en' => 'Latvia', 'desc_ar' => 'لاتفيا'],
        ['code' => 'LY', 'desc_en' => 'Libya', 'desc_ar' => 'ليبيا'],
        ['code' => 'MA', 'desc_en' => 'Morocco', 'desc_ar' => 'المغرب'],
        ['code' => 'MC', 'desc_en' => 'Monaco', 'desc_ar' => 'موناكو'],
        [
            'code' => 'MD',
            'desc_en' => 'Moldova (Republic of)',
            'desc_ar' => 'مولدافيا',
        ],
        ['code' => 'ME', 'desc_en' => 'Montenegro', 'desc_ar' => 'الجبل الأسود'],
        [
            'code' => 'MF',
            'desc_en' => 'Saint Martin (French Part)',
            'desc_ar' => 'تجمع سان مارتين',
        ],
        ['code' => 'MG', 'desc_en' => 'Madagascar', 'desc_ar' => 'مدغشقر'],
        [
            'code' => 'MH',
            'desc_en' => 'Marshall Islands',
            'desc_ar' => 'جزر مارشال',
        ],
        ['code' => 'MK', 'desc_en' => 'North Macedonia', 'desc_ar' => 'مقدونيا'],
        ['code' => 'ML', 'desc_en' => 'Mali', 'desc_ar' => 'مالي'],
        ['code' => 'MM', 'desc_en' => 'Myanmar', 'desc_ar' => 'ميانمار'],
        ['code' => 'MN', 'desc_en' => 'Mongolia', 'desc_ar' => 'منغوليا'],
        ['code' => 'MO', 'desc_en' => 'Macao', 'desc_ar' => 'ماكاو'],
        [
            'code' => 'MP',
            'desc_en' => 'Northern Mariana Islands',
            'desc_ar' => 'جزر ماريانا الشمالية',
        ],
        ['code' => 'MQ', 'desc_en' => 'Martinique', 'desc_ar' => 'مارتينيك'],
        ['code' => 'MR', 'desc_en' => 'Mauritania', 'desc_ar' => 'موريتانيا'],
        ['code' => 'MS', 'desc_en' => 'Montserrat', 'desc_ar' => 'مونتسرات'],
        ['code' => 'MT', 'desc_en' => 'Malta', 'desc_ar' => 'مالطا'],
        ['code' => 'MU', 'desc_en' => 'Mauritius', 'desc_ar' => 'موريشيوس'],
        ['code' => 'MV', 'desc_en' => 'Maldives', 'desc_ar' => 'جزر المالديف'],
        ['code' => 'MW', 'desc_en' => 'Malawi', 'desc_ar' => 'ملاوي'],
        ['code' => 'MX', 'desc_en' => 'Mexico', 'desc_ar' => 'المكسيك'],
        ['code' => 'MY', 'desc_en' => 'Malaysia', 'desc_ar' => 'ماليزيا'],
        ['code' => 'MZ', 'desc_en' => 'Mozambique', 'desc_ar' => 'موزمبيق'],
        ['code' => 'NA', 'desc_en' => 'Namibia', 'desc_ar' => 'ناميبيا'],
        [
            'code' => 'NC',
            'desc_en' => 'New Caledonia',
            'desc_ar' => 'كاليدونيا الجديدة',
        ],
        ['code' => 'NE', 'desc_en' => 'Niger', 'desc_ar' => 'النيجر'],
        [
            'code' => 'NF',
            'desc_en' => 'Norfolk Island',
            'desc_ar' => 'جزيرة نورفولك',
        ],
        ['code' => 'NG', 'desc_en' => 'Nigeria', 'desc_ar' => 'نيجيريا'],
        ['code' => 'NI', 'desc_en' => 'Nicaragua', 'desc_ar' => 'نيكاراجوا'],
        ['code' => 'NL', 'desc_en' => 'Netherlands', 'desc_ar' => 'هولندا'],
        ['code' => 'NO', 'desc_en' => 'Norway', 'desc_ar' => 'النرويج'],
        ['code' => 'NP', 'desc_en' => 'Nepal', 'desc_ar' => 'نيبال'],
        ['code' => 'NR', 'desc_en' => 'Nauru', 'desc_ar' => 'نورو'],
        ['code' => 'NU', 'desc_en' => 'Niue', 'desc_ar' => 'نيوي'],
        ['code' => 'NZ', 'desc_en' => 'New Zealand', 'desc_ar' => 'نيوزيلاندا'],
        ['code' => 'OM', 'desc_en' => 'Oman', 'desc_ar' => 'عمان'],
        ['code' => 'PA', 'desc_en' => 'Panama', 'desc_ar' => 'بنما'],
        ['code' => 'PE', 'desc_en' => 'Peru', 'desc_ar' => 'بيرو'],
        [
            'code' => 'PF',
            'desc_en' => 'French Polynesia',
            'desc_ar' => 'بولينزيا الفرنسية',
        ],
        [
            'code' => 'PG',
            'desc_en' => 'Papua New Guinea',
            'desc_ar' => 'بابوا غينيا الجديدة',
        ],
        ['code' => 'PH', 'desc_en' => 'Philippines', 'desc_ar' => 'الفيلبين'],
        ['code' => 'PK', 'desc_en' => 'Pakistan', 'desc_ar' => 'باكستان'],
        ['code' => 'PL', 'desc_en' => 'Poland', 'desc_ar' => 'بولندا'],
        [
            'code' => 'PM',
            'desc_en' => 'Saint Pierre and Miquelon',
            'desc_ar' => 'سان بيير وميكلون',
        ],
        ['code' => 'PN', 'desc_en' => 'Pitcairn', 'desc_ar' => 'بتكايرن'],
        ['code' => 'PR', 'desc_en' => 'Puerto Rico', 'desc_ar' => 'بورتوريكو'],
        [
            'code' => 'PS',
            'desc_en' => 'Palestinian, State of',
            'desc_ar' => 'فلسطين',
        ],
        ['code' => 'PT', 'desc_en' => 'Portugal', 'desc_ar' => 'البرتغال'],
        ['code' => 'PW', 'desc_en' => 'Palau', 'desc_ar' => 'بالاو'],
        ['code' => 'PY', 'desc_en' => 'Paraguay', 'desc_ar' => 'باراجواي'],
        ['code' => 'QA', 'desc_en' => 'Qatar', 'desc_ar' => 'قطر'],
        ['code' => 'RE', 'desc_en' => 'Réunion', 'desc_ar' => 'روينيون'],
        ['code' => 'RO', 'desc_en' => 'Romania', 'desc_ar' => 'رومانيا'],
        ['code' => 'RS', 'desc_en' => 'Serbia', 'desc_ar' => 'صربيا'],
        ['code' => 'RU', 'desc_en' => 'Russian Federation', 'desc_ar' => 'روسيا'],
        ['code' => 'RW', 'desc_en' => 'Rwanda', 'desc_ar' => 'رواندا'],
        ['code' => 'SA', 'desc_en' => 'Saudi Arabia', 'desc_ar' => 'السعودية'],
        ['code' => 'SB', 'desc_en' => 'Solomon Islands', 'desc_ar' => 'جزر سليمان'],
        ['code' => 'SC', 'desc_en' => 'Seychelles', 'desc_ar' => 'سيشل'],
        ['code' => 'SD', 'desc_en' => 'Sudan', 'desc_ar' => 'السودان'],
        ['code' => 'SE', 'desc_en' => 'Sweden', 'desc_ar' => 'السويد'],
        ['code' => 'SG', 'desc_en' => 'Singapore', 'desc_ar' => 'سنغافورة'],
        [
            'code' => 'SH',
            'desc_en' => 'Saint Helena, Ascension and Tristan da Cunha',
            'desc_ar' => 'سانت هيلينا وأسينشين وتريستان دا كونا',
        ],
        ['code' => 'SI', 'desc_en' => 'Slovenia', 'desc_ar' => 'سلوفينيا'],
        [
            'code' => 'SJ',
            'desc_en' => 'Svalbard and Jan Mayen',
            'desc_ar' => 'سفالبارد ويان ماين',
        ],
        ['code' => 'SK', 'desc_en' => 'Slovakia', 'desc_ar' => 'سلوفاكيا'],
        ['code' => 'SL', 'desc_en' => 'Sierra Leone', 'desc_ar' => 'سيراليون'],
        ['code' => 'SM', 'desc_en' => 'San Marino', 'desc_ar' => 'سان مارينو'],
        ['code' => 'SN', 'desc_en' => 'Senegal', 'desc_ar' => 'السنغال'],
        ['code' => 'SO', 'desc_en' => 'Somalia', 'desc_ar' => 'الصومال'],
        ['code' => 'SR', 'desc_en' => 'Suriname', 'desc_ar' => 'سورينام'],
        ['code' => 'SS', 'desc_en' => 'South Sudan', 'desc_ar' => 'جنوب السودان'],
        [
            'code' => 'ST',
            'desc_en' => 'Sao Tome and Principe',
            'desc_ar' => 'ساو تومي وبرينسيب',
        ],
        ['code' => 'SV', 'desc_en' => 'El Salvador', 'desc_ar' => 'السلفادور'],
        [
            'code' => 'SX',
            'desc_en' => 'Sint Maarten (Dutch Part)',
            'desc_ar' => 'سينت مارتن',
        ],
        ['code' => 'SY', 'desc_en' => 'Syrian Arab Republic', 'desc_ar' => 'سوريا'],
        ['code' => 'SZ', 'desc_en' => 'Eswatini', 'desc_ar' => 'سوازيلاند'],
        [
            'code' => 'TC',
            'desc_en' => 'Turks and Caicos Islands',
            'desc_ar' => 'جزر توركس وكايكوس',
        ],
        ['code' => 'TD', 'desc_en' => 'Chad', 'desc_ar' => 'تشاد'],
        [
            'code' => 'TF',
            'desc_en' => 'French Southern Territories',
            'desc_ar' => 'أراض فرنسية جنوبية وأنتارتيكية',
        ],
        ['code' => 'TG', 'desc_en' => 'Togo', 'desc_ar' => 'توجو'],
        ['code' => 'TH', 'desc_en' => 'Thailand', 'desc_ar' => 'تايلند'],
        ['code' => 'TJ', 'desc_en' => 'Tajikistan', 'desc_ar' => 'طاجكستان'],
        ['code' => 'TK', 'desc_en' => 'Tokelau', 'desc_ar' => 'توكيلو'],
        ['code' => 'TL', 'desc_en' => 'Timor-Leste', 'desc_ar' => 'تيمور الشرقية'],
        ['code' => 'TM', 'desc_en' => 'Turkmenistan', 'desc_ar' => 'تركمانستان'],
        ['code' => 'TN', 'desc_en' => 'Tunisia', 'desc_ar' => 'تونس'],
        ['code' => 'TO', 'desc_en' => 'Tonga', 'desc_ar' => 'تونجا'],
        ['code' => 'TR', 'desc_en' => 'Turkey', 'desc_ar' => 'تركيا'],
        [
            'code' => 'TT',
            'desc_en' => 'Trinidad and Tobago',
            'desc_ar' => 'ترينيداد وتوباغو',
        ],
        ['code' => 'TV', 'desc_en' => 'Tuvalu', 'desc_ar' => 'توفالو'],
        [
            'code' => 'TW',
            'desc_en' => 'Taiwan (Province of China)',
            'desc_ar' => 'تايوان',
        ],
        [
            'code' => 'TZ',
            'desc_en' => 'Tanzania, United Republic of',
            'desc_ar' => 'تانزانيا',
        ],
        ['code' => 'UA', 'desc_en' => 'Ukraine', 'desc_ar' => 'أوكرانيا'],
        ['code' => 'UG', 'desc_en' => 'Uganda', 'desc_ar' => 'أوغندا'],
        [
            'code' => 'UM',
            'desc_en' => 'United States Minor Outlying Islands',
            'desc_ar' => 'جزر الولايات المتحدة الصغيرة النائية',
        ],
        [
            'code' => 'US',
            'desc_en' => 'United States of America',
            'desc_ar' => 'الولايات المتحدة',
        ],
        ['code' => 'UY', 'desc_en' => 'Uruguay', 'desc_ar' => 'أورجواي'],
        ['code' => 'UZ', 'desc_en' => 'Uzbekistan', 'desc_ar' => 'أوزبكستان'],
        ['code' => 'VA', 'desc_en' => 'Holy See', 'desc_ar' => 'الفاتيكان'],
        [
            'code' => 'VC',
            'desc_en' => 'Saint Vincent and the Grenadines',
            'desc_ar' => 'سانت فينسنت والغرينادين',
        ],
        [
            'code' => 'VE',
            'desc_en' => 'Venezuela (Bolivarian Republic of)',
            'desc_ar' => 'فنزويلا',
        ],
        [
            'code' => 'VG',
            'desc_en' => 'Virgin Islands (British)',
            'desc_ar' => 'جزر العذراء البريطانية',
        ],
        [
            'code' => 'VI',
            'desc_en' => 'Virgin Islands (U.S.)',
            'desc_ar' => 'جزر العذراء الأمريكية',
        ],
        ['code' => 'VN', 'desc_en' => 'Viet Nam', 'desc_ar' => 'فيتنام'],
        ['code' => 'VU', 'desc_en' => 'Vanuatu', 'desc_ar' => 'فانواتو'],
        [
            'code' => 'WF',
            'desc_en' => 'Wallis and Futuna',
            'desc_ar' => 'والس وفوتونا',
        ],
        ['code' => 'WS', 'desc_en' => 'Samoa', 'desc_ar' => 'ساموا'],
        ['code' => 'YE', 'desc_en' => 'Yemen', 'desc_ar' => 'اليمن'],
        ['code' => 'YT', 'desc_en' => 'Mayotte', 'desc_ar' => 'مايوت'],
        ['code' => 'ZA', 'desc_en' => 'South Africa', 'desc_ar' => 'جنوب أفريقيا'],
        ['code' => 'ZM', 'desc_en' => 'Zambia', 'desc_ar' => 'زامبيا'],
        ['code' => 'ZW', 'desc_en' => 'Zimbabwe', 'desc_ar' => 'زيمبابوي'],
    ];
}
