<?php

namespace App\Domains\ETA\Models;

use Illuminate\Database\Eloquent\Model;
use Sushi\Sushi;

class CurrencyCodes extends Model
{
    use Sushi;

    /**
     * Get Sushi array record.
     *
     * @var array
     */
    protected array $rows = [
        ['code' => 'AED', 'description' => 'UAE Dirham'],
        ['code' => 'AFN', 'description' => 'Afghani'],
        ['code' => 'ALL', 'description' => 'Lek'],
        ['code' => 'AMD', 'description' => 'Armenian Dram'],
        ['code' => 'ANG', 'description' => 'Netherlands Antillean Guilder'],
        ['code' => 'AOA', 'description' => 'Kwanza'],
        ['code' => 'ARS', 'description' => 'Argentine Peso'],
        ['code' => 'AUD', 'description' => 'Australian Dollar'],
        ['code' => 'AWG', 'description' => 'Aruban Florin'],
        ['code' => 'AZN', 'description' => 'Azerbaijan Manat'],
        ['code' => 'BAM', 'description' => 'Convertible Mark'],
        ['code' => 'BBD', 'description' => 'Barbados Dollar'],
        ['code' => 'BDT', 'description' => 'Taka'],
        ['code' => 'BGN', 'description' => 'Bulgarian Lev'],
        ['code' => 'BHD', 'description' => 'Bahraini Dinar'],
        ['code' => 'BIF', 'description' => 'Burundi Franc'],
        ['code' => 'BMD', 'description' => 'Bermudian Dollar'],
        ['code' => 'BND', 'description' => 'Brunei Dollar'],
        ['code' => 'BOB', 'description' => 'Boliviano'],
        ['code' => 'BOV', 'description' => 'Mvdol'],
        ['code' => 'BRL', 'description' => 'Brazilian Real'],
        ['code' => 'BSD', 'description' => 'Bahamian Dollar'],
        ['code' => 'BTN', 'description' => 'Ngultrum'],
        ['code' => 'BWP', 'description' => 'Pula'],
        ['code' => 'BYN', 'description' => 'Belarusian Ruble'],
        ['code' => 'BZD', 'description' => 'Belize Dollar'],
        ['code' => 'CAD', 'description' => 'Canadian Dollar'],
        ['code' => 'CDF', 'description' => 'Congolese Franc'],
        ['code' => 'CHE', 'description' => 'WIR Euro'],
        ['code' => 'CHF', 'description' => 'Swiss Franc'],
        ['code' => 'CHW', 'description' => 'WIR Franc'],
        ['code' => 'CLF', 'description' => 'Unidad de Fomento'],
        ['code' => 'CLP', 'description' => 'Chilean Peso'],
        ['code' => 'CNY', 'description' => 'Yuan Renminbi'],
        ['code' => 'COP', 'description' => 'Colombian Peso'],
        ['code' => 'COU', 'description' => 'Unidad de Valor Real'],
        ['code' => 'CRC', 'description' => 'Costa Rican Colon'],
        ['code' => 'CUC', 'description' => 'Peso Convertible'],
        ['code' => 'CUP', 'description' => 'Cuban Peso'],
        ['code' => 'CVE', 'description' => 'Cabo Verde Escudo'],
        ['code' => 'CZK', 'description' => 'Czech Koruna'],
        ['code' => 'DJF', 'description' => 'Djibouti Franc'],
        ['code' => 'DKK', 'description' => 'Danish Krone'],
        ['code' => 'DOP', 'description' => 'Dominican Peso'],
        ['code' => 'DZD', 'description' => 'Algerian Dinar'],
        ['code' => 'EGP', 'description' => 'Egyptian Pound'],
        ['code' => 'ERN', 'description' => 'Nakfa'],
        ['code' => 'ETB', 'description' => 'Ethiopian Birr'],
        ['code' => 'EUR', 'description' => 'Euro'],
        ['code' => 'FJD', 'description' => 'Fiji Dollar'],
        ['code' => 'FKP', 'description' => 'Falkland Islands Pound'],
        ['code' => 'GBP', 'description' => 'Pound Sterling'],
        ['code' => 'GEL', 'description' => 'Lari'],
        ['code' => 'GHS', 'description' => 'Ghana Cedi'],
        ['code' => 'GIP', 'description' => 'Gibraltar Pound'],
        ['code' => 'GMD', 'description' => 'Dalasi'],
        ['code' => 'GNF', 'description' => 'Guinean Franc'],
        ['code' => 'GTQ', 'description' => 'Quetzal'],
        ['code' => 'GYD', 'description' => 'Guyana Dollar'],
        ['code' => 'HKD', 'description' => 'Hong Kong Dollar'],
        ['code' => 'HNL', 'description' => 'Lempira'],
        ['code' => 'HRK', 'description' => 'Kuna'],
        ['code' => 'HTG', 'description' => 'Gourde'],
        ['code' => 'HUF', 'description' => 'Forint'],
        ['code' => 'IDR', 'description' => 'Rupiah'],
        ['code' => 'ILS', 'description' => 'New Israeli Sheqel'],
        ['code' => 'INR', 'description' => 'Indian Rupee'],
        ['code' => 'IQD', 'description' => 'Iraqi Dinar'],
        ['code' => 'IRR', 'description' => 'Iranian Rial'],
        ['code' => 'ISK', 'description' => 'Iceland Krona'],
        ['code' => 'JMD', 'description' => 'Jamaican Dollar'],
        ['code' => 'JOD', 'description' => 'Jordanian Dinar'],
        ['code' => 'JPY', 'description' => 'Yen'],
        ['code' => 'KES', 'description' => 'Kenyan Shilling'],
        ['code' => 'KGS', 'description' => 'Som'],
        ['code' => 'KHR', 'description' => 'Riel'],
        ['code' => 'KMF', 'description' => 'Comorian Franc '],
        ['code' => 'KPW', 'description' => 'North Korean Won'],
        ['code' => 'KRW', 'description' => 'Won'],
        ['code' => 'KWD', 'description' => 'Kuwaiti Dinar'],
        ['code' => 'KYD', 'description' => 'Cayman Islands Dollar'],
        ['code' => 'KZT', 'description' => 'Tenge'],
        ['code' => 'LAK', 'description' => 'Lao Kip'],
        ['code' => 'LBP', 'description' => 'Lebanese Pound'],
        ['code' => 'LKR', 'description' => 'Sri Lanka Rupee'],
        ['code' => 'LRD', 'description' => 'Liberian Dollar'],
        ['code' => 'LSL', 'description' => 'Loti'],
        ['code' => 'LYD', 'description' => 'Libyan Dinar'],
        ['code' => 'MAD', 'description' => 'Moroccan Dirham'],
        ['code' => 'MDL', 'description' => 'Moldovan Leu'],
        ['code' => 'MGA', 'description' => 'Malagasy Ariary'],
        ['code' => 'MKD', 'description' => 'Denar'],
        ['code' => 'MMK', 'description' => 'Kyat'],
        ['code' => 'MNT', 'description' => 'Tugrik'],
        ['code' => 'MOP', 'description' => 'Pataca'],
        ['code' => 'MRU', 'description' => 'Ouguiya'],
        ['code' => 'MUR', 'description' => 'Mauritius Rupee'],
        ['code' => 'MVR', 'description' => 'Rufiyaa'],
        ['code' => 'MWK', 'description' => 'Malawi Kwacha'],
        ['code' => 'MXN', 'description' => 'Mexican Peso'],
        ['code' => 'MXV', 'description' => 'Mexican Unidad de Inversion (UDI)'],
        ['code' => 'MYR', 'description' => 'Malaysian Ringgit'],
        ['code' => 'MZN', 'description' => 'Mozambique Metical'],
        ['code' => 'NAD', 'description' => 'Namibia Dollar'],
        ['code' => 'NGN', 'description' => 'Naira'],
        ['code' => 'NIO', 'description' => 'Cordoba Oro'],
        ['code' => 'NOK', 'description' => 'Norwegian Krone'],
        ['code' => 'NPR', 'description' => 'Nepalese Rupee'],
        ['code' => 'NZD', 'description' => 'New Zealand Dollar'],
        ['code' => 'OMR', 'description' => 'Rial Omani'],
        ['code' => 'PAB', 'description' => 'Balboa'],
        ['code' => 'PEN', 'description' => 'Sol'],
        ['code' => 'PGK', 'description' => 'Kina'],
        ['code' => 'PHP', 'description' => 'Philippine Peso'],
        ['code' => 'PKR', 'description' => 'Pakistan Rupee'],
        ['code' => 'PLN', 'description' => 'Zloty'],
        ['code' => 'PYG', 'description' => 'Guarani'],
        ['code' => 'QAR', 'description' => 'Qatari Rial'],
        ['code' => 'RON', 'description' => 'Romanian Leu'],
        ['code' => 'RSD', 'description' => 'Serbian Dinar'],
        ['code' => 'RUB', 'description' => 'Russian Ruble'],
        ['code' => 'RWF', 'description' => 'Rwanda Franc'],
        ['code' => 'SAR', 'description' => 'Saudi Riyal'],
        ['code' => 'SBD', 'description' => 'Solomon Islands Dollar'],
        ['code' => 'SCR', 'description' => 'Seychelles Rupee'],
        ['code' => 'SDG', 'description' => 'Sudanese Pound'],
        ['code' => 'SEK', 'description' => 'Swedish Krona'],
        ['code' => 'SGD', 'description' => 'Singapore Dollar'],
        ['code' => 'SHP', 'description' => 'Saint Helena Pound'],
        ['code' => 'SLL', 'description' => 'Leone'],
        ['code' => 'SOS', 'description' => 'Somali Shilling'],
        ['code' => 'SRD', 'description' => 'Surinam Dollar'],
        ['code' => 'SSP', 'description' => 'South Sudanese Pound'],
        ['code' => 'STN', 'description' => 'Dobra'],
        ['code' => 'SVC', 'description' => 'El Salvador Colon'],
        ['code' => 'SYP', 'description' => 'Syrian Pound'],
        ['code' => 'SZL', 'description' => 'Lilangeni'],
        ['code' => 'THB', 'description' => 'Baht'],
        ['code' => 'TJS', 'description' => 'Somoni'],
        ['code' => 'TMT', 'description' => 'Turkmenistan New Manat'],
        ['code' => 'TND', 'description' => 'Tunisian Dinar'],
        ['code' => 'TOP', 'description' => 'Pa’anga'],
        ['code' => 'TRY', 'description' => 'Turkish Lira'],
        ['code' => 'TTD', 'description' => 'Trinidad and Tobago Dollar'],
        ['code' => 'TWD', 'description' => 'New Taiwan Dollar'],
        ['code' => 'TZS', 'description' => 'Tanzanian Shilling'],
        ['code' => 'UAH', 'description' => 'Hryvnia'],
        ['code' => 'UGX', 'description' => 'Uganda Shilling'],
        ['code' => 'USD', 'description' => 'US Dollar'],
        ['code' => 'USN', 'description' => 'US Dollar (Next day)'],
        ['code' => 'UYI', 'description' => 'Uruguay Peso en Unidades Indexadas (UI)'],
        ['code' => 'UYU', 'description' => 'Peso Uruguayo'],
        ['code' => 'UYW', 'description' => 'Unidad Previsional'],
        ['code' => 'UZS', 'description' => 'Uzbekistan Sum'],
        ['code' => 'VED', 'description' => 'Bolívar Soberano'],
        ['code' => 'VES', 'description' => 'Bolívar Soberano'],
        ['code' => 'VND', 'description' => 'Dong'],
        ['code' => 'VUV', 'description' => 'Vatu'],
        ['code' => 'WST', 'description' => 'Tala'],
        ['code' => 'XAF', 'description' => 'CFA Franc BEAC'],
        ['code' => 'XAG', 'description' => 'Silver'],
        ['code' => 'XAU', 'description' => 'Gold'],
        [
            'code' => 'XBA',
            'description' => 'Bond Markets Unit European Composite Unit (EURCO)',
        ],
        [
            'code' => 'XBB',
            'description' => 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
        ],
        [
            'code' => 'XBC',
            'description' => 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
        ],
        [
            'code' => 'XBD',
            'description' =>
                'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
        ],
        ['code' => 'XCD', 'description' => 'East Caribbean Dollar'],
        ['code' => 'XDR', 'description' => 'SDR (Special Drawing Right)'],
        ['code' => 'XOF', 'description' => 'CFA Franc BCEAO'],
        ['code' => 'XPD', 'description' => 'Palladium'],
        ['code' => 'XPF', 'description' => 'CFP Franc'],
        ['code' => 'XPT', 'description' => 'Platinum'],
        ['code' => 'XSU', 'description' => 'Sucre'],
        [
            'code' => 'XTS',
            'description' => 'Codes specifically reserved for testing purposes',
        ],
        ['code' => 'XUA', 'description' => 'ADB Unit of Account'],
        [
            'code' => 'XXX',
            'description' =>
                'The codes assigned for transactions where no currency is involved',
        ],
        ['code' => 'YER', 'description' => 'Yemeni Rial'],
        ['code' => 'ZAR', 'description' => 'Rand'],
        ['code' => 'ZMW', 'description' => 'Zambian Kwacha'],
        ['code' => 'ZWL', 'description' => 'Zimbabwe Dollar'],
    ];
}
